[project]
name = "neurosim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "absl-py>=0.7.0",
    "gradio>=6.14.0",
    "numpy>=2.4.1",
    "prettytable>=3.17.0",
    "pyyaml>=6.0.3",
    "scipy>=1.17.0",
    "setuptools>=80.9.0",
    "sphinx-glpi-theme>=0.6",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
    "python-dotenv>=1.0.0",
]
